bower.json, d2l-alignment-list.html, d2l-alignment.html, d2l-outcome.html
Needs:
- https://github.com/Brightspace/d2l-hm-constants-behavior/pull/72
- https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/8
=> integrate with level of achievements selector

d2l-outcome.html, demo/request-mock.html
=> some ui updates

d2l-alignment-update.html
=> use already inspected target for checkbox-change event

bower.json, d2l-alignment-list.html, localize-behavior.html
Cause screen readers to announce when an alignment has been removed with the X button
=> DE31982 -- Notify screen readers when an alignment has been removed

d2l-activity-alignment-tag-list.js, d2l-activity-alignment-tags.js, package.json
Added  a readonly `empty` property that can be checked to see if there are any alignments
You can now do
```
<d2l-activity-alignment-tags
....
empty="{{_isAlignmentListEmpty}}"
>
```
and then `_isAlignmentListEmpty` will be set when the alignment list becomes empty or non-empty
=> Added  a readonly empty property

d2l-alignment-list.js, d2l-alignment.js, localize-behavior.js, package.json
Split alignments into two lists for direct and indirect alignments
=> Indirect Alignments

d2l-select-outcomes.js
For [this rubrics PR](https://github.com/Brightspace/d2l-rubric/pull/476)
=> Putting overflow hidden on select outcomes

d2l-activity-alignments.js, d2l-alignment-list.js, d2l-alignment-update.js, d2l-select-outcomes.js
added check for empty so that rubric editor can hide the outcome button when alignments are empty
=> added check for empty alignment

d2l-activity-alignment-tag-list.js, localize-behavior.js
The massive diff is due to [https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf](stackoverflow)
=> change alt text to browse outcome

d2l-alignment-update.js, d2l-select-outcomes.js
This will make the scrollbar in d2l-rubric work.
Thanks to Chris K and Jeff
=> Make scrollbar work

d2l-alignment-update.js
bug fix when entities is undefined
=> bug fix for undefined entities

d2l-alignment-update.js, d2l-select-outcomes.js
so the button will appear first before it disappear
=> set empty list default to false

d2l-user-alignment-list.js, package.json
d2l-user-alignment-list was missing slot for show-select-outcomes button
=> Fix for UserActivityUsage

d2l-alignment-update.js, d2l-select-outcomes.js
- adding horizontal scroll on small screen
- break word
=> WCAG US106973

package.json
the existing value is causing duplicate versions in folio-app
=> multi-select semver

d2l-activity-alignment-tag-list.js, d2l-activity-alignment-tags.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/391701573856
=> Add configuration parameter to tag to either support save/cancel or autosave

d2l-activity-alignment-tag-list.js, d2l-activity-alignment-tags.js
https://rally1.rallydev.com/#/29180338367d/detail/userstory/389962037972
=> US116429 - Support showing only direct alignments

d2l-activity-alignment-tag-list.js
These changes only impact the deferred save use-case, and the introduction of the `_mappings` array is a refactoring to make it easier to refer back to the previous version of `_mappings` from within `_getAlignmentToOutcomeMap`.
To fix the refreshing: When the entity updates and `_getAlignmentHrefs` is called, it resets the intents and outcomes map objects. This will allow us to be certain of their count as they are being reloaded. `_getAlignmentToOutcomeMap` then skips updating the `_mappings` prop until both the intents and outcomes count match the alignment subentities on the entity, which means that the intents and outcomes have all been loaded and are ready to be rendered.
https://rally1.rallydev.com/#/29180338367d/detail/userstory/399753264276
=> US117890 Stop alignment tags from refreshing unnecessarily when using deferred save

TestCafe/LOA_on_Outcomes.js, package.json
Updating multi-select to 4.x to keep it up to date with the new version being used in facet-filter-sort.
=> Multi Select Version Bump

build/lang/ar.js, build/lang/cy.js, build/lang/da.js, build/lang/de.js, build/lang/en.js, build/lang/es-es.js, build/lang/es.js, build/lang/fr-fr.js, build/lang/fr.js, build/lang/ja.js, build/lang/ko.js, build/lang/nl.js, build/lang/pt.js, build/lang/sv.js, build/lang/tr.js, build/lang/zh-tw.js, build/lang/zh.js, langtools/build.template
Language source data was not namespaced to the current components name. Could cause issues.
=> Fix issue with language loading

package-lock.json, package.json
=> Bump version to 2.0.24

d2l-activity-alignment-tag-list.js, package-lock.json, package.json
This enables deleting of tags via keyboard commands.
=> US114403 - Fix issue with tag delete

package-lock.json, package.json
This includes accessibility and general keyboard navigation inputs.
=> US114403 - Update to latest multi-select

d2l-activity-alignment-tag-list.js, package-lock.json, package.json
=> US114403 - Fix styling issues more

d2l-activity-alignment-tag-list.js, package-lock.json, package.json
Recommend viewing with [white-space diff off](https://github.com/Brightspace/d2l-activity-alignments/pull/160/files?w=1).
This puts the `+` button back into it's original spot after some fixes to multi-select. Was moved outside due to styling issues but was not desired behaviour.
=> US114403 - Fix button flow

package-lock.json, package.json
Releasing translations to 20.21.4 and master.
=> Bump version to 2.1.5

build/lang/ar.js, build/lang/cy.js, build/lang/da.js, build/lang/de.js, build/lang/en.js, build/lang/es-es.js, build/lang/es.js, build/lang/fr-fr.js, build/lang/fr-on.js, build/lang/fr.js, build/lang/ja.js, build/lang/ko.js, build/lang/nl.js, build/lang/pt.js, build/lang/sv.js, build/lang/tr.js, build/lang/zh-tw.js, build/lang/zh.js, langtools/build.template, localize-behavior.js, package-lock.json, package.json
This is working towards serge JavaScript setup instead of JSON setup.
=> Simplify localization loader
